syntax = "proto3";

package toando.hosting.v1alpha1;

option go_package = "api.toando.de/go/hosting/v1alpha1;hostingv1alpha1";

service AppService {
    rpc CreateApp(CreateAppRequest) returns (App);
    rpc GetApp(GetAppRequest) returns (App);
    rpc ListApps(ListAppsRequest) returns (ListAppsResponse);
    rpc DeleteApp(DeleteAppRequest) returns (DeleteAppResponse);
}

message App {
    string id = 1;
    string name = 2;
}

message CreateAppRequest {
    string name = 1;
}

message GetAppRequest {
    string id = 1;
}

message ListAppsRequest {}

message ListAppsResponse {
    repeated App apps = 1;
}

message DeleteAppRequest {
    string id = 1;
}
message DeleteAppResponse {}